name: Build cvWrap for Maya 2022

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout cvwrap with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Auto Download Maya 2022 Devkit
        uses: blurstudio/mayaModuleActions/getMayaDevkit@v1
        id: devkit
        with:
          maya: '2022'
          cache: true

      - name: Configure and Build
        shell: pwsh
        run: |
          $devkit = "${{ steps.devkit.outputs.devkit-path }}"
          Write-Host "Devkit successfully loaded at: $devkit"
          
          # 生成工程并编译
          cmake -B build -G "Visual Studio 17 2022" -A x64 `
            -DMAYA_VERSION=2022 `
            -DDEVKIT_LOCATION="$devkit" `
            -DMAYA_LOCATION="$devkit"
            
          cmake --build build --config Release

      - name: Upload cvWrap.mll
        uses: actions/upload-artifact@v4
        with:
          name: cvWrap_Maya2022_Windows
          path: |
            build/Release/cvWrap.mll
            build/**/cvWrap.mll
